services:
  nginx:
    image: nginx:alpine
    container_name: nginx-worker-demo
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    restart: unless-stopped
